version: 0.2

phases:
 build:
   commands:
     - echo Build started on `date`
     - npm install
     - npm run build
 post_build:
   commands:
     - echo Build completed on `date`
    #  - cp deploy/appspec.yml appspec.yml
artifacts:
 files:
   - /.next/**/*
  #  - appspec.yml
# cache:
#  paths:
#    - '/root/.npm/**/*'